Operation:DeletePublisher
OperationDisplayName:Delete Publisher
OperationType:RDFERWOperation
OperationGroup:PlatformImageRepositoryManagementOperation
OperationGroupDisplayName:Platform Image Repository Management Operation
ApproverParameterNeeded:Y
ApproverLinkParameterNeeded:Y
HelperFunctionName:DeletePublisher
Parameter:string:subscription:Subscription:SubscriptionParam:AcisSMEParameter
Parameter:string:publisherCode:Publisher Code:PublisherCodeParam:AcisSMETextParameter