Operation:EnablePublishedImage
OperationDisplayName:Enable Published Image (TSQ)
OperationType:RDFERWOperation
OperationGroup:PlatformImageRepositoryManagementOperation
OperationGroupDisplayName:na
ApproverParameterNeeded:Y
ApproverLinkParameterNeeded:Y
HelperFunctionName:EnablePublishedImage
Parameter:string:subscriptionId:Subscription Id:subscription:na
Parameter:string:platformImageName:Image Name:PlatformImageName:AcisSMETextParameter
