Operation:FindTenantNameByDip
OperationDisplayName:Find Tenant Name By DIP (Fabric)
OperationType:RDFEROOperation
OperationGroup:SubscriptionOperation
OperationGroupDisplayName:na
ApproverParameterNeeded:N
ApproverLinkParameterNeeded:N
HelperFunctionName:FindTenantNameByDip
Parameter:string:fabricClusterName:Fabric Cluster:FabricClusterName:AcisSMETextParameter
Parameter:string:deviceIPAddress:DIP:DeviceIPAddress:AcisSMETextParameter
