Operation:ListPublishedAssetEntities
OperationDisplayName:List Published Asset Entities (TSQ)
OperationType:RDFEROOperation
OperationGroup:PlatformImageRepositoryManagementOperation
OperationGroupDisplayName:na
ApproverParameterNeeded:N
ApproverLinkParameterNeeded:N
HelperFunctionName:ListPublishedAssetEntities
Parameter:string:assetType:Asset Type:AssetType:AcisSMETextParameter
Parameter:string:originalName:Original Name:OriginalName:AcisSMETextParameter
