Operation:RegisterExtension
OperationDisplayName:Register Extension
OperationType:RDFERWOperation
OperationGroup:OSManagementOperation
OperationGroupDisplayName:na
ApproverParameterNeeded:Y
ApproverLinkParameterNeeded:Y
HelperFunctionName:RegisterExtension
Parameter:string:subscriptionId:Subscription Id:subscription:na
Parameter:string:extensionFile:Extension File:ExtensionFile:AcisSMEFileParameter
