Operation:UnregisterCacheAccount
OperationDisplayName:Unregister Cache Account
OperationType:RDFERWOperation
OperationGroup:PlatformImageRepositoryManagementOperation
OperationGroupDisplayName:Don't Need
ApproverParameterNeeded:Y
ApproverLinkParameterNeeded:Y
HelperFunctionName:UnregisterCacheAccount
Parameter:string:accountname:Cache Account Name:CacheAccountName:AcisSMETextParameter