Operation:UpdateExtension
OperationDisplayName:Update Extension
OperationType:RDFERWOperation
OperationGroup:OSManagementOperation
OperationGroupDisplayName:na
ApproverParameterNeeded:Y
ApproverLinkParameterNeeded:Y
HelperFunctionName:UpdateExtension
Parameter:string:subscriptionId:Subscription Id:subscription:na
Parameter:string:extensionFile:Extension File:ExtensionFile:AcisSMEFileParameter
